name: Documentation Request 📃
description: Change regarding improving the docs to be more accessible
title: "[Docs]"
body:
  - type: textarea
    attributes:
      label: Category of documentation update
      description: |
        What category does this change fall under. For example Typo error, New category addition, Rephrasing the sentences, fixing broken links etc.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Describe the change you think might work
      description: Please describe the change & need of change in atmost detail possible.
    validations:
      required: false

  - type: checkboxes
    id: no-duplicate-issues
    attributes:
      label: "Checklist"
      options:
        - label: "I have checked the existing issues."
          required: true

        - label: "I am a IWOC'24 contributor."
          required: false
